# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [1]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [2]:
# Import torch


# Create random tensor
import torch

rand_tensor = torch.rand(7,7)
rand_tensor

tensor([[0.0687, 0.5318, 0.7778, 0.8386, 0.4401, 0.2388, 0.3691],
        [0.5118, 0.1801, 0.1110, 0.7105, 0.0488, 0.6824, 0.0834],
        [0.6454, 0.1047, 0.8401, 0.8391, 0.8599, 0.8255, 0.9075],
        [0.3443, 0.9026, 0.3430, 0.6671, 0.9035, 0.0078, 0.1187],
        [0.1859, 0.2065, 0.6757, 0.0842, 0.3233, 0.0278, 0.9734],
        [0.2021, 0.8325, 0.3418, 0.9376, 0.7539, 0.2219, 0.9668],
        [0.5369, 0.6939, 0.4492, 0.0208, 0.3001, 0.7215, 0.7795]])

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [3]:
# Create another random tensor
tensor_2 = torch.rand(1,7)
tensor_2_reshaped = tensor_2.T
matrixmulti = torch.matmul(rand_tensor, tensor_2_reshaped)
rand_tensor
# Perform matrix multiplication


tensor([[0.0687, 0.5318, 0.7778, 0.8386, 0.4401, 0.2388, 0.3691],
        [0.5118, 0.1801, 0.1110, 0.7105, 0.0488, 0.6824, 0.0834],
        [0.6454, 0.1047, 0.8401, 0.8391, 0.8599, 0.8255, 0.9075],
        [0.3443, 0.9026, 0.3430, 0.6671, 0.9035, 0.0078, 0.1187],
        [0.1859, 0.2065, 0.6757, 0.0842, 0.3233, 0.0278, 0.9734],
        [0.2021, 0.8325, 0.3418, 0.9376, 0.7539, 0.2219, 0.9668],
        [0.5369, 0.6939, 0.4492, 0.0208, 0.3001, 0.7215, 0.7795]])

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [4]:
# Set manual seed
RANDOM_SEED= 0
torch.manual_seed(RANDOM_SEED)
tensor_1 = torch.rand(7,7)
torch.manual_seed(RANDOM_SEED)
tensor_two = torch.rand(1,7)
tensor_two_reshaped = tensor_two.T
tensor = torch.matmul(tensor_1,tensor_two_reshaped)
tensor
# Create two random tensors


# Matrix multiply tensors


tensor([[1.5985],
        [1.1173],
        [1.2741],
        [1.6838],
        [0.8279],
        [1.0347],
        [1.2498]])

### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [5]:
# Set random seed on the GPU
import torch
RANDOM_SEED = 1234
seed = torch.manual_seed(RANDOM_SEED)
device = "cuda" if torch.cuda.is_available() else "cpu"




### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [13]:
# Set random seed
RANDOM_SEED =1234
torch.manual_seed(RANDOM_SEED)


# Check for access to GPU
device
# Create two random tensors on GPU
rand_1 = torch.rand(2,3).to(device)
RANDOM_SEED =1234
torch.manual_seed(RANDOM_SEED)
rand_2 = torch.rand(2,3).to(device)

print(f"{rand_1}", rand_1.device)
print(f"{rand_2}", rand_2.device)


tensor([[0.0290, 0.4019, 0.2598],
        [0.3666, 0.0583, 0.7006]], device='cuda:0') cuda:0
tensor([[0.0290, 0.4019, 0.2598],
        [0.3666, 0.0583, 0.7006]], device='cuda:0') cuda:0



### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [17]:
# Perform matmul on tensor_A and tensor_B
matmul_rand = torch.matmul(rand_1, rand_2.T)
matmul_rand, matmul_rand.shape


(tensor([[0.2299, 0.2161],
         [0.2161, 0.6287]], device='cuda:0'),
 torch.Size([2, 2]))

### 8. Find the maximum and minimum values of the output of 7.

In [16]:
# Find max
torch.max(matmul_rand)
# Find min
torch.min(matmul_rand)


tensor(0.2161, device='cuda:0')

### 9. Find the maximum and minimum index values of the output of 7.

In [18]:
# Find arg max
torch.argmax(matmul_rand)

# Find arg min
torch.argmin(matmul_rand)


tensor(1, device='cuda:0')


### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [23]:
# Set seed
RANDOM_SEED=7
torch.manual_seed(RANDOM_SEED)

# Create random tensor
rand = torch.rand(1,1,1,10)
rand

# Remove single dimensions
per_rand = torch.squeeze(rand)
per_rand.shape
# Print out tensors and their shapes


torch.Size([10])